import tkinter as tk

root=tk.Tk()
#root.geometry('400*400')
l1=tk.Label(root,text="enter somthing")
l2=tk.Label(root,text="enter somthing")
l3=tk.Label(root,text="result")
t1=tk.Entry(root,width=30)
t2=tk.Entry(root,width=30)
t3=tk.Entry(root,width=30)
l1.grid(row=0,column=0)
t1.grid(row=0,column=1)
l2.grid(row=1,column=0)
t2.grid(row=1,column=1)
l3.grid(row=2,column=0)
t3.grid(row=2,column=1)
b1=tk.Button(root,text="show hello")
b2=tk.Button(root,text="clear")
root.mainloop()